### ISSUE TITLE
8pt font ?

### ISSUE THREAD

**Issue by tablatronix** [squix78/esp8266-oled-ssd1306#100]
Is there no 8pt builtin ?

**Comment by tablatronix** [comment]
anyone have or recommend a 5x7 font for this library ?

**Comment by squix78** [comment]
It is actually quite easy to create one yourself: http://oleddisplay.squix.ch/#/home

Do you agree that we can close this issue?

**Comment by tablatronix** [comment]
It is easy, thanks.

Although I have not found a good extra small 5x7 with 1pixel 
Can I convert the adafrut gfx font ?
