### ISSUE TITLE
Implement missing  OLEDDisplayUi::setLoadingDrawFunction() in OLEDDisplayUi.cpp

### ISSUE THREAD

**Issue by artkeller** [squix78/esp8266-oled-ssd1306#102]
When I tried to use **setLoadingDrawFunction()** I realized the missing code in **OLEDDisplayUi.cpp**.

After adding the 1-liner everything worked fine:

 `// -/----- Loading Process -----\-

void OLEDDisplayUi::setLoadingDrawFunction(LoadingDrawFunction loadingDrawFunction) {
  this->loadingDrawFunction = loadingDrawFunction;
}

void OLEDDisplayUi::runLoadingProcess(LoadingStage* stages, uint8_t stagesCount) {
...
 `

Thanks for your lib - very useful!

Thomas

**Comment by FWeinb** [comment]
Thanks for catching this. I added a PR that implements this.
