### ISSUE TITLE
Available fonts

### ISSUE THREAD

**Issue by pinanunes** [squix78/esp8266-oled-ssd1306#123]
Fantastic library!
I wanted to use on a project tall but condensed font (http://www.1001fonts.com/attentica-4f-font.html#license) but is not available on your web converter.
I've manage to convert it with fontconverter from Adafruit_GFX, but they have a different format than your fonts. Is there a way to convert from one format to the other?

**Comment by squix78** [comment]
I just added it to the converter. Please check and close the issue if you agree it has been resolved:-)

**Comment by pinanunes** [comment]
You are the man!
Works great thanks!
On a display here:[http://imgur.com/a/vtXzz]
