### ISSUE TITLE
Manual frame change

### ISSUE THREAD

**Issue by pinanunes** [squix78/esp8266-oled-ssd1306#130]
Is OLEDDisplayUi only possible in auto mode?
I have a project with a rotary encoder to change the information on the display, but It would be nice if I could add the sliding frame behaviour depending on the direction we turn the encoder (left or right).
Is not a major issue but "would look nice".

**Comment by zharijs** [comment]
You can use:
void setFrames(FrameCallback* frameFunctions, uint8_t frameCount);
Check OLEDDisplayUi.h for all features. Comments are plenty and helpful in that file too.

**Comment by pinanunes** [comment]
OK! thanks!
My bad skipped that!
