### ISSUE TITLE
Is it possible to add \n?

### ISSUE THREAD

**Issue by stony2k** [squix78/esp8266-oled-ssd1306#15]
Is it possible to add \n for breaking text into a new line for method drawString or drawStringMaxWidth?

**Comment by FWeinb** [comment]
Support will be in `3.0.0`. Thanks for reporting.

**Comment by Oliverr** [comment]
@FWeinb Was this added?

**Comment by FWeinb** [comment]
Yes this was added, See: https://github.com/squix78/esp8266-oled-ssd1306/blob/master/OLEDDisplay.cpp#L424-L451
