### ISSUE TITLE
SSD1306Demo.ino typos

### ISSUE THREAD

**Issue by matricies** [squix78/esp8266-oled-ssd1306#20]
This:

    // You can change the transition that is used
    // SLIDE_LEFT, SLIDE_RIGHT, SLIDE_TOP, SLIDE_DOWN

should be (TOP should be **UP**):

    // You can change the transition that is used
    // SLIDE_LEFT, SLIDE_RIGHT, SLIDE_UP, SLIDE_DOWN

This: 

    display->setFont(ArialMT_Plain_16);
    display->drawString(0 + x, 20, "Arial 16");

should be (missing **'+ Y'**):

    display->setFont(ArialMT_Plain_16);
    display->drawString(0 + x, 20 + y, "Arial 16");

This:

    display->setFont(ArialMT_Plain_24);
    display->drawString(0 + x, 34, "Arial 24");

should be (missing **'+ Y'**):

    display->setFont(ArialMT_Plain_24);
    display->drawString(0 + x, 34 + y, "Arial 24");

Also, the images here: https://github.com/squix78/esp8266-oled-ssd1306
do not match what the current version of SSD1306Demo.ino displays.

(Thanks for a fantastic SSD1306 driver, BTW.)

**Comment by matricies** [comment]
Thanks.

**Comment by fantasymaker-cn** [comment]
This helps! But example file dosen't update yet.
