### ISSUE TITLE
No free remainingTimeBudget

### ISSUE THREAD

**Issue by dimmas375** [squix78/esp8266-oled-ssd1306#25]
Hi,

Just created a program based on your example for WeMos D1 and noticed that part of `loop()` inside `if (remainingTimeBudget > 0)` doesn't run.
Is it safe to run some code outside this condition?

One more thing: changing fps to 25 or lesser makes insane frames switching, like 3-5 frames in one second.

**Comment by FWeinb** [comment]
This will be fixed in `3.0.0`. Thanks for reporting.
