### ISSUE TITLE
Can't draw Bitmap

### ISSUE THREAD

**Issue by sirowain** [squix78/esp8266-oled-ssd1306#27]
I'm trying to draw a bitmap using the drawBitmap() function, but I can't show the image correctly.
I created the array using LCD Assistant ([http://en.radzio.dxp.pl/bitmap_converter](http://en.radzio.dxp.pl/bitmap_converter)) and replaced the one in the demo project but the image is messed up. I also tried drawXbm() without results. How did you prepared the array for the WiFi logo in the demo?

**Comment by squix78** [comment]
Hi Riccardo

I recommend using GIMP to export the pictures as 1 bit XBM format. I don't remember exactly how to generate the bitmaps...
