### ISSUE TITLE
contributing & naming conventions

### ISSUE THREAD

**Issue by hixfield** [squix78/esp8266-oled-ssd1306#28]
I am an experienced C++ programmer (embedded). I love the work you have done and would like to participate. However, I noticed that the naming conventions are not ideal. Would you allow me to update the naming of the variables? I also have a few other updates in mind after this.

**Comment by squix78** [comment]
Hi Hixfield. You are more than welcome to help. My problem is that I currently have other priorities in my spare time projects and don't have much time to maintain this project. @FWeinb already started a V3.0.0 branch and it probably makes a lot of sense to continue work on that branch, also to avoid breaking downstream dependencies... What do you think?

**Comment by hixfield** [comment]
That sounds good to me. @FWeinb are you open for collaboration?

**Comment by FWeinb** [comment]
Sure. I made an PR #16 Would really like to clean that up. The PR is against the dev branch for 3.0. Would be good to merge that one first and you can than pick it up and modify as you like.

**Comment by hixfield** [comment]
@squix78 would you agree? How do you see the rights issue? Should we get the required rights from you?

**Comment by squix78** [comment]
Done. Please check if you have now commit permissions.

**Comment by FWeinb** [comment]
Thanks. I can commit. I would now merge the Outstanding PR and @hixfield could start refactoring from there.

**Comment by hixfield** [comment]
Sounds like a plan! Let me know when I can pull it and from where :)

**Comment by squix78** [comment]
Great. Thank you guys in advance!

**Comment by FWeinb** [comment]
Just merged it to the `dev-branch-3.0.0` branch. You can now checkout that branch and work on the code.

**Comment by FWeinb** [comment]
I would say you crate a new branch of of the `dev-branch-3.0.0` and than do a PR against the dev-branch when you are done. Me and @squix78 can than review your changes and when everything looks good we merge it.

**Comment by hixfield** [comment]
ok that sound good

**Comment by hixfield** [comment]
By the way this is the naming convention I have been using for many years, everybody ok with this?
Variable names context prefix:
m_ : member variable
g_ : global variable

Variable names type prefix:
sz : zero terminated character array string
p : pointer
n : signed number
u : unsinged number
c : class

camelCase for variables, functions
PascalCase for objects, types
constants or defines in UPPERCASE


Example:

const in MAXSIZE = 255
#define MAXSIZESTRING 255

class CMyClass : CSomeRootClass {
private :
char m_szSearch[MAXSIZESTRING];
int m_nCharIndex;
char * m_pIndexPointer;

public:

int add(int nNumber1, int nNumber2);
}

**Comment by FWeinb** [comment]
As long as we maintain the public api where possible I am fine with that. I would not rename the SSD1306 class just to conform with this naming schema.
