### ISSUE TITLE
Compiler error "redefinition of 'const char ArialMT_Plain_10 []'"

### ISSUE THREAD

**Issue by RetepV** [squix78/esp8266-oled-ssd1306#30]
This is caused by the multiple inclusion of SSD1306Fonts.h. If I choose Sketch->Include Library->ESP8266 Oled Driver... in the Arduino IDE, this is included in my sketch:
```
#include <SSD1306.h>
#include <SSD1306Fonts.h>
#include <SSD1306Ui.h>
```
But SSD1306Fonts.h is also included in SSD1306Ui.h. So either the include of SSD1306Fonts.h in the sketch is unnecessary, or a ```#pragma once``` should be added to SSD1306Fonts.h.

But really, the file should be split into a .h and a .cpp file. The definitions should go in the .h file, the implementation should go in the .cpp file.

**Comment by FWeinb** [comment]
This will be fixed in 3.0.0. Thanks for reporting!
