### ISSUE TITLE
Does dev 3.0 branch work with newest Arduino IDE?

### ISSUE THREAD

**Issue by stony2k** [squix78/esp8266-oled-ssd1306#31]

**Comment by squix78** [comment]
Yes, I'm currently trying it. In the examples I had to move the methods below the loop() method up so they would be declared before they were used. If you agree we can close this issue?

**Comment by stony2k** [comment]
Yes I do, thank you :)

Taki
Am 19.05.2016 22:30 schrieb "squix78" <notifications@github.com>:
