### ISSUE TITLE
Simple example...

### ISSUE THREAD

**Issue by kmitchel** [squix78/esp8266-oled-ssd1306#33]
Please provide a simple/minimalist example.

You may want to do something with keywords or something, to help make this library easier to find.

**Comment by squix78** [comment]
I understand your request for a simple example. I guess you are mostly interested in an example without the frames? But I can't follow on the keywords. Do you mind to explain? Do you mean the keywords in the library.json? From which platform did you try to use the library? Arduino IDE, Platformio?

**Comment by kmitchel** [comment]
You should make this library easier to find--some how. I messed around with a lot of stuff that didn't work, until I came across your stuff by accident. 

So some search engine optimization stuff...anyone who searches for esp8266 and oled should come here first.

Thank you for the code.
