### ISSUE TITLE
remove or add frames during runtime

### ISSUE THREAD

**Issue by lighthousebulb** [squix78/esp8266-oled-ssd1306#34]
Is it possible to remove or add frames during runtime?

**Comment by spants** [comment]
+1 I'd like to do this too

**Comment by squix78** [comment]
I would say yes, have you tried to call ui.setFrames(frames, frameCount); again with your new frames? I tried it on the dev branch and it works? Would you mind to confirm this for the master branch?

**Comment by FWeinb** [comment]
Using `setFrames`during runtime can be dangerous. In 3.0.0, we should ensure that we reset all state values that are used internally. If the frameCount is less than the old frameCount there could be crashed due to invalid array accesses etc.

**Comment by FWeinb** [comment]
Closed by #42
