### ISSUE TITLE
Add print() and println() to UI class

### ISSUE THREAD

**Issue by squix78** [squix78/esp8266-oled-ssd1306#35]
- Allow a self-scrolling ui e.g. for debug output
- add print() and println()

**Comment by FWeinb** [comment]
We should implement Arduinos [`Print.h`](https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/cores/arduino/Print.h) in `OLEDDisplay.h` after that we could add some functions like `setLogBufferSize(rows)` that would define how many rows would be displayed. 
To draw the log we could than have a `drawLogArea(uint16_t x, uint16_t y, uint16_t width)` function.
