### ISSUE TITLE
Add progress bar function to UI class

### ISSUE THREAD

**Issue by squix78** [squix78/esp8266-oled-ssd1306#36]
Add a function that simply lets the user draw a progress bar.

**Comment by FWeinb** [comment]
I have a rough function for this:

```       
void drawProgressBar(uin8t_t x, uint8_t y, uint8_t height, uint_t width, uint8_t progress) { 
          display->drawRect(x, y, width, height);
          display->fillRect(x + 2, y + 2, ((width - 3) * ((float)progress / 100)), height - 3);
}
```

**Comment by squix78** [comment]
I have seen that, but I now have implemented it and (I think) it looks prettier than just the squared progress bar, more "IOS like". I first had it in the UI class, but then moved it to the core class, it felt better there. What do you think?

**Comment by FWeinb** [comment]
I think It should ne on the UI class.

**Comment by FWeinb** [comment]
This was done in 57e2ff322a306467a2bbed2a395edba9620da60f
