### ISSUE TITLE
feature request, multiple oled displays

### ISSUE THREAD

**Issue by matbor** [squix78/esp8266-oled-ssd1306#39]
Feature request or example.. would be good to run multiple displays, ie. weather on one and the time on the other.

**Comment by CaptainStouf** [comment]
Hi, I believe you could do that already using displays with configurable addresses and declaring each display with
```
// Initialize the OLED display on address 0x3c
SSD1306   display(0x3c, I2C_SDA, I2C_SCL);
```
_(untested)_

**Comment by FWeinb** [comment]
Correct, that is the way to go.
