### ISSUE TITLE
Name changes are a terrible idea

### ISSUE THREAD

**Issue by RogerSchaefer** [squix78/esp8266-oled-ssd1306#48]
Changing the names of files from SSD1306xxxxx to OLEDDisplayxxxxx without changing the name of the library itself is a terrible thing to do.

Arduino has a pop-up that opens whenever you open the program.  It urges you to update libraries and boards.  Anyone in the world who has used your "esp8266-oled-ssd1306" and has clicked on update will have their sketches blown up.

This caused me two hours of grief.

Luckily i had Ver 2.0.2 in a backup.

Please fix this quickly.

Roger
Oldmicroguy

**Comment by FWeinb** [comment]
This library is following [semver](http://semver.org/) a versioning schema that is willed used in the development community and recommended in the [`Arduino Library specification`](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format). A major version change (from 2.0.0 to 3.0.0) indicates `breaking changes` to the public API. We did the best we can making updating as easy as possible by writing an [Upgrade Guide](https://github.com/squix78/esp8266-oled-ssd1306/blob/master/UPGRADE-3.0.md). 

We develop this library in our spare time and provide it with absolutely no warranty whatsoever.
I am sorry that this caused you trouble but please don't be rude and say that we need do fix things quickly. We are trying our best here.
