### ISSUE TITLE
drawString with Umlauts are not working

### ISSUE THREAD

**Issue by lighthousebulb** [squix78/esp8266-oled-ssd1306#5]
When I use a Umlaut in a display.drawString-Function inside a frameCallback it shows Garbage on the Display.

```
display.drawString(0 + x, 25 + y, "äöüÄÖÜ");
```
gives me something like: 

![20151211_160443](https://cloud.githubusercontent.com/assets/12849008/11746990/1ccf3b80-a021-11e5-881c-a0a301b2c82a.jpg)

Happens with v1.0.1 of the ssd1306 oled library.

**Comment by squix78** [comment]
Thank you for reporting. I think I know how to fix the issue. I think characters above ASCII 127 will be encoded as Unicode or other encoding

**Comment by squix78** [comment]
Hi @lighthousebulb 
I just added a fix and released a new version of the library. Can you please confirm that the latest release fixes the Umlauts? If yes please close this issue...
Cheers,
Dani

**Comment by lighthousebulb** [comment]
Works perfect so far!
Thanks!
