### ISSUE TITLE
drawStringMaxWidth can cut off words

### ISSUE THREAD

**Issue by simap** [squix78/esp8266-oled-ssd1306#61]
First, thanks for an awesome library!

In some cases the drawStringMaxWidth call can cut off words at the right edge of the screen. In this case 'diam' is cut off, and 'tempor' could have wrapped to the next line as well.

Here is Roboto 12 with this code:
```c
display.setFont(Roboto_12);
display.setTextAlignment(TEXT_ALIGN_LEFT);
display.drawStringMaxWidth(0, 0, 128,
      "Lorem ipsum\n dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore." );
```

![drawstringmaxwidth](https://cloud.githubusercontent.com/assets/1427631/16708281/e580dc52-45a1-11e6-8cac-73ddeb0c1f32.jpg)

**Comment by FWeinb** [comment]
Thanks for reporting this. I made a PR #62 that fixes it. This will be release in `3.2.3`
