### ISSUE TITLE
drawRect and fillRect produce rects of different size

### ISSUE THREAD

**Issue by igrr** [squix78/esp8266-oled-ssd1306#66]
Currently the code in OLEDDisplay::drawRect is as follows:
```c++
  drawHorizontalLine(x, y, width);
  drawVerticalLine(x, y, height);
  drawVerticalLine(x + width, y, height);
  drawHorizontalLine(x, y + height, width);
```
Compared to `fillRect` function, this draws a rectangle which is 1 pixel wider and 1 pixel higher. Also it lacks a pixel at the lower-right corner. 

![media-20160710](https://cloud.githubusercontent.com/assets/4349050/16712203/35416962-46b2-11e6-82d7-d33099e10c55.jpg)

If I change that to `x + width - 1` and `y + height - 1`, i get same size as for `fillRect`.
I'm not sure if such a "fix" qualifies as a change in API though :)

And by the way, why is `fillRect` using `drawHorizontalLine`? Isn't `drawVerticalLine` faster because it can set up to 8 pixels at a time?

**Comment by FWeinb** [comment]
Thanks for reporting, this won't qualify as a change in API because this is clearly a bug in the code. Good idea to improve `fillRect` by using `drawVerticalLine`!

**Comment by FWeinb** [comment]
Thanks for reporting. We decided to release this in `4.0.0` with some other fixes that could possible break existing code.
