### ISSUE TITLE
Black text on white background.

### ISSUE THREAD

**Issue by filmote** [squix78/esp8266-oled-ssd1306#74]
I have recently upgraded from V2.0.2 to the latest code and have issues when rendering black text on a white background.  This used to work as expected in version 2 but now the rendering results in garbage.  Is this a bug or am I missing something in the changes?

**Comment by FWeinb** [comment]
This is a regression, thanks for reporting. This will be fixed in a future version.

**Comment by filmote** [comment]
Great!  I will continue using the V2 library for the moment.  Look forward to seeing a fix in future.

**Comment by FWeinb** [comment]
This will be finally fixed in `3.2.4`
