### ISSUE TITLE
Cyrillic fonts

### ISSUE THREAD

**Issue by utya1988** [squix78/esp8266-oled-ssd1306#79]
Hello. I really like you project WeatherClock, but i cannot use cyrillic fonts. and  i don't know to do this. Thanks.

**Comment by FWeinb** [comment]
I don't know the inner workings of Cyrillic fonts. I worked on Arabic fonts in #56 but didn't have a solution at that time. In the future there will be the possibility to write your own custom mapper function for mapping Unicode to the internal character table.

**Comment by FWeinb** [comment]
I think this is out of scope of this library. The building blocks will be in `3.2.4` but as none of us can speak cyrillic or arabic it is hard for us to implement this.

**Comment by colesnicov** [comment]
Hi.
Any progress in promoting cyrilic and extended fonts?

**Comment by Voha888** [comment]
> peak cyrillic or arabic it is hard for us to implement this.

Thanks, cool solution, I'll try to use it. On your part, there is a proposal to consider the possibility of adding UTF-8 encoding support to the font files, not just ASCII, this will allow users to create multilingual fonts themselves
