### ISSUE TITLE
Dual displays

### ISSUE THREAD

**Issue by middelbh** [squix78/esp8266-oled-ssd1306#81]
Hi! I though to be smart and connect two 0.96" oled displays to my EPS8266, each with the same address but each with different SDA and SDC ports (as I still have sufficient of them in the flight tracker..)

So this is part of the code:
.......
const int I2C_display_ADDRESS = 0x3c;
const int SDA_PIN = 4;
const int SDC_PIN = 2;
const int SDA_PIN2= 12;
const int SDC_PIN2= 13;
SSD1306Wire     display1(I2C_display_ADDRESS, SDA_PIN, SDC_PIN);
SSD1306Wire     display2(I2C_display_ADDRESS, SDA_PIN2, SDC_PIN2);**
......
Compiling the program however gave the following error:

.....
sketch\flightscan_test3.ino.cpp.o: In function `__static_initialization_and_destruction_0':
C:\Users\Hans\AppData\Local\Temp\arduino_modified_sketch_472887/flightscan_test3.ino:195: undefined reference to `vtable for OLEDDisplay'
collect2.exe: error: ld returned 1 exit status
exit status 1
.....

My question: is it possible to have dual displays without changing the I2C addresses in this way?

**Comment by FWeinb** [comment]
I just tested it using Arduino 1.6.9 with this code: 
```c++
#include <SSD1306Wire.h>

const int I2C_display_ADDRESS = 0x3c;
const int SDA_PIN = 4;
const int SDC_PIN = 2;
const int SDA_PIN2= 12;
const int SDC_PIN2= 13;

SSD1306Wire display1(I2C_display_ADDRESS, SDA_PIN, SDC_PIN);
SSD1306Wire display2(I2C_display_ADDRESS, SDA_PIN2, SDC_PIN2);

void setup() {
}

void loop() {
}
```

And everything is compiling, could you please post the complete sketch you are trying to run.

**Comment by middelbh** [comment]
Hi,

 

Attached my sketch..

I added several extra’s, they work without problem. Just when I add the line

 

SSD1306Wire display2(I2C_display_ADDRESS, SDA_PIN2, SDC_PIN2);

 

The compilation gives errors…

 

I hope you can help!

 

Regards,

 

hans

Van: FWeinb [mailto:notifications@github.com] 
Verzonden: donderdag 25 augustus 2016 11:54
Aan: squix78/esp8266-oled-ssd1306 <esp8266-oled-ssd1306@noreply.github.com>
CC: middelbh <middelbeek@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [squix78/esp8266-oled-ssd1306] Dual displays (#81)

 

I just tested it using Arduino 1.6.9 with this code: 

#include <SSD1306Wire.h>
 
const int I2C_display_ADDRESS = 0x3c;
const int SDA_PIN = 4;
const int SDC_PIN = 2;
const int SDA_PIN2= 12;
const int SDC_PIN2= 13;
 
SSD1306Wire display1(I2C_display_ADDRESS, SDA_PIN, SDC_PIN);
SSD1306Wire display2(I2C_display_ADDRESS, SDA_PIN2, SDC_PIN2);
 
void setup() {
}
 
void loop() {
}

And everything is compiling, could you please post the complete sketch you are trying to run.

**Comment by FWeinb** [comment]
Sorry but the sketch isn't attached.

**Comment by middelbh** [comment]
I tried to attach it as an rtf, but here the .ino…

 

Van: FWeinb [mailto:notifications@github.com] 
Verzonden: donderdag 25 augustus 2016 12:09
Aan: squix78/esp8266-oled-ssd1306 <esp8266-oled-ssd1306@noreply.github.com>
CC: middelbh <middelbeek@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [squix78/esp8266-oled-ssd1306] Dual displays (#81)

 

Sorry but the sketch isn't attached.

**Comment by FWeinb** [comment]
I looks like it isn't possible to attach it via email.

**Comment by middelbh** [comment]
I will try this afternoon to attach ..

**Comment by middelbh** [comment]
Her is the zipped .ino file.
Hope you can find the problem!

Hans
[flightscan_test4.zip](https://github.com/squix78/esp8266-oled-ssd1306/files/436951/flightscan_test4.zip)

**Comment by middelbh** [comment]
By the way, in the .zip I only have the mentioned programlines, I do not yet use display2 furtheron in the sketch as the compile did not succeed.

**Comment by FWeinb** [comment]
So had a minute to look a this. Kinda strange. I boiled it down to this issue: 

```
#include "SSD1306Wire.h"

const int I2C_display_ADDRESS = 0x3c;
const int SDA_PIN = 4;
const int SDC_PIN = 2;

SSD1306Wire     display1(I2C_display_ADDRESS, 4, 2);
SSD1306Wire     display2(I2C_display_ADDRESS, 5, 3);

//String thisWillBreakIt;

void setup(){}
void loop(){}
```

when you uncomment `String thisWillBreakIt` definition it will break the code. I have honestly no idea why this is happening.

**Comment by middelbh** [comment]
Thanks a lot! I will try ASAP! Interesting to understand why this happens!

Hans

**Comment by middelbh** [comment]
Hi, I did as proposed, but same error again...

C:\Users\Hans\AppData\Local\Temp\arduino_modified_sketch_76867/flightscan_test4.ino:196: undefined reference to `vtable for OLEDDisplay'

collect2.exe: error: ld returned 1 exit status
