### ISSUE TITLE
problem with text and negative y values

### ISSUE THREAD

**Issue by tzapu** [squix78/esp8266-oled-ssd1306#85]
Hi,
I am trying to minimize lost space around a text by trying to put it a few pixels off screen on the vertical.

At the bottom, it works fine, at the top, o big chunk of the text seems to be missing with 10px font and -2 y position.

In screenshot, middle and right hand text on overlay had -2 as y.

Cheers
![img_2774](https://cloud.githubusercontent.com/assets/2983312/18433854/76436920-78f2-11e6-9f89-9ec51d6eaf33.JPG)

**Comment by FWeinb** [comment]
This was fixed in #65 but got never released.
