### ISSUE TITLE
Use multiple OLEDs via I2C

### ISSUE THREAD

**Issue by derhannesb** [squix78/esp8266-oled-ssd1306#87]
When trying to use multiple OLEDs I get the following error:

> Linking .pioenvs\nodemcuv2\firmware.elf
> .pioenvs\nodemcuv2\src\main.o:(.text._ZN11OLEDDisplayC2Ev[_ZN11OLEDDisplayC5Ev]+0x0): undefined reference to `vtable for OLEDDisplay'

Code:
`SH1106 display(0x3c, D1, D2);`
`SH1106 display2(0x3c, D3, D4);`

The same happens when using different i2c addresses:
`SH1106 display(0x3c, D1, D2);`
`SH1106 display2(0x3d, D1, D2);`

**Comment by FWeinb** [comment]
I did not have time to do a proper release but this issue is fixed on `master`. See [this](https://github.com/squix78/esp8266-oled-ssd1306/issues/81#issuecomment-242910568) for how to fix this yourself. I hope there will be another release some time.
