### ISSUE TITLE
void disableAllIndicator(); function is missing

### ISSUE THREAD

**Issue by jblb** [squix78/esp8266-oled-ssd1306#88]
Function is present in documentation but there is no implementation.

**Comment by FWeinb** [comment]
Sorry but we didn't have time to do another release yet. `master` is the latest version here on github but not the latest released. I hope we can do a release soon.

**Comment by jblb** [comment]
Ok I didn't look at this point.  At least there is a typo in README file: functions are called witout final s disableAllIndicator() vs disableAllIndicators()
