### ISSUE TITLE
0.96 Inch was Ok But Wrong Operation on 1.3 Inch

### ISSUE THREAD

**Issue by bizteco0** [squix78/esp8266-oled-ssd1306#93]
I loaded SSD1306ClockDemo to ESP8266 with 0.96 Inch OLED based on SSD1306 driver. that was ok,
and i tried it to 1.3 Inch OLED based on SSD1306 driver. But It did not work properly. that is.
screen was distorted.
I think that resolution of display does not matched your library.
Please let me know how to solve it.

**Comment by FWeinb** [comment]
You need to add more information to let us help you. Please attach an example that is working on the 0.96 inch oled but noch on the 1.3 inch oled and please specify the used hardware some more. You can reopen this issue.
