### ISSUE TITLE
Display - rotate by 180?

### ISSUE THREAD

**Issue by erkobg** [squix78/esp8266-oled-ssd1306#94]
Hello,
Is it possible to rotate the screen by 180 degrees and how to do it?

Regards.

**Comment by erkobg** [comment]
Ops - I found it - display has a method : **flipScreenVertically**

**Comment by RudyFiero** [comment]
Yes. I have an orientation sensor that I use to trigger it. But it has been some time since I have been into the code so I can't tell you how.
