### ISSUE TITLE
SSD1306SimpleDemo problem with activating the right mode

### ISSUE THREAD

**Issue by hoekbrwr** [squix78/esp8266-oled-ssd1306#95]
I am not a C++ expert so I do not understand what to do to activate the right variables for I2c modus using brzo. Also The designation of the SCL and SDA connections is odd, D3 and D5. Does this mean GPIO14 and GPIO2 on a Sparkfun thing dev? These pins are designated as SCL and SDA!
I thought removing the slashes in the apropriate lines would do, but when I do so it gives a compile error SSD1306SimpleDemo:53: error: 'D3' does not name a type

 D3 -> SDA
.
.
.
.
.

One might expect when taking away the comment slashes the syntax on that line is OK,I can not guess what type of var you like to have.

**Comment by FWeinb** [comment]
`D3` and `D5` are the pin names for nodeMCU like esp8266 dev boards. You can find the real GPIO numbers [here](https://github.com/esp8266/Arduino/blob/master/variants/nodemcu/pins_arduino.h)
