### ISSUE TITLE
Disable Frame indicator cannot be unabled

### ISSUE THREAD

**Issue by hoekbrwr** [squix78/esp8266-oled-ssd1306#96]
I have problems using the OLEDDisplayUi.disableAllIndicators() method. I can see it in the imported file like any other usable method. It just says it is not a member of this class! In the README.MD  it is called disableAllIndicator(), typo??? This is the only thing I could not use, but further on this is a great piece of SW for the small OLED SSD1306!
Is there another method to get rid off the frame indicator?

**Comment by FWeinb** [comment]
I fixed the documentation in the Readme. Using `disableAllIndicators()` will disable the drawing of any indicator for all frames. Thanks for reporting.
